version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "gradle"
    # Look for `build.gradle` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
